var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/kamar-belakang/socials/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__11vqb71._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09atk3z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__038l5oq._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09gt57q._.js")
R.c("server/chunks/ssr/src_1xthrcw._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/src_app_kamar-belakang_layout_tsx_16x6tjl._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xvc6th._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1y1r1mk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_18_d8l1._.js")
R.m(66834)
module.exports=R.m(66834).exports
