var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/kamar-belakang/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__19tyevd._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0w6mzq5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09atk3z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__038l5oq._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09gt57q._.js")
R.c("server/chunks/ssr/src_1xthrcw._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/src_app_kamar-belakang_layout_tsx_16x6tjl._.js")
R.c("server/chunks/ssr/_next-internal_server_app_kamar-belakang_page_actions_1s643nf.js")
R.m(52744)
module.exports=R.m(52744).exports
